### ISSUE TITLE
Return markup preprocessor only

### ISSUE THREAD

**Issue by RedHatter** [halfnelson/svelte-native-preprocessor#6]
Currently svelte-native-preprocessor returns an object with a markup key this complicates using other preprocessors with it.
```js
preprocess: Object.assign(svelteNativePreprocessor(), { style: postcssSvelte() })
```

Only a markup preproccesor is used so there's no reason not to just return the one function.
```js
preprocess: {
  markup: svelteNativePreprocessor(),
  style: postcssSvelte()
}
```
This is the standard that most svelte preprocessors use.

**Comment by halfnelson** [comment]
I think it is best to stick to the preprocessor spec https://svelte.dev/docs#svelte_preprocess
you could always use the array form,  then it would just be
`preprocess: [SvelteNativePreprocessor(), { style: postcssSvelte() })`
or keep what you have and use
```js
preprocess: {
  markup: svelteNativePreprocessor().markup,
  style: postcssSvelte()
}
```
